import Head from 'next/head'
import { useQuery } from 'react-query'
import Navbar from '../components/navbar'
import TodoList from '../components/todoList'
import { fetchTodos } from '../helper/helper'
import AuthContextProvider from '../contexts/auth'

export const getServerSideProps = async (ctx) => {
  let cookie

  if (ctx.req.headers.cookie == undefined) {
    cookie = false
  }
  else {
    cookie = true
  }

  return {
    props: {
      cookie: cookie
    }
  }
}

export default function Home({ cookie }) {
  let { data } = useQuery('todos', fetchTodos)

  return (
    <div>
      <Head>
        <title>Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthContextProvider cookie={cookie}>
        <Navbar />
        <TodoList data={data} />
      </AuthContextProvider>
    </div>

  )
}
